# -*- coding: utf-8 -*-
"""ProjectDatasci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PkSHZi2UpYi2GLjMfGD84p-XyZw0pEV

1. Import Library & Load Data Collection
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("Results.csv", encoding ='utf-8')

print("อ่านไฟล์สำเร็จ")
print(df.head())

df["result"] = df.apply(
    lambda x: "HomeWin" if x["home_score"] > x["away_score"]
    else "AwayWin" if x["home_score"] < x["away_score"]
    else "Draw",
    axis=1
)

df[["home_team","away_team","home_score","away_score","result"]].head()

""" 2. Data Preprocessing"""

x = df.shape[0]
y = df.shape[1]
print("มี",x,"แถวและ",y,"คอลัมน์")

print("\nข้อมูลที่หายไป")
print(df.isnull().sum())

print("\nประเภทของข้อมูล")
print(df.dtypes)

#เลือกข้อมูลที่จะนำไปใช้
X = df[["home_team","away_team","tournament","neutral"]]

#เลือกข้อมูลที่จะให้โมเดลทำนาย
y = df["result"]

#แปลงข้อมูลเป็นตัวเลข
X = pd.get_dummies(X)

#Check Results
X.head()

#แบ่งข้อมูล Train/Test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""3. Model Selection"""

#เลือก Model ที่จะ Train
model = RandomForestClassifier(n_estimators=100)

"""4. Model Training"""

#Train Model
model.fit(X_train, y_train)

"""Predicted Results"""

#ทำนายผล
y_pred = model.predict(X_test)

"""5. Model Evaluation"""

#ดูความแม่นยำ
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

"""6. Model Tuning"""

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)

print("Cross Validation Accuracy:", scores.mean())

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [200, 300, 500],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)

best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))